import { Dimensions, Platform, StyleSheet } from 'react-native';

const { height } = Dimensions.get('window');
const compactHeight = height < 850;
const cardPadding = compactHeight ? 16 : 20;

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#100F05',
  },
  background: {
    flex: 1,
    minHeight: height,
  },
  overlay: {
    flex: 1,
  },
  formScroll: {
    flex: 1,
  },
  content: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 58 : 40,
    paddingBottom: compactHeight ? 260 : 320,
  },
  languagePill: {
    alignSelf: 'flex-end',
    minWidth: compactHeight ? 132 : 146,
    height: compactHeight ? 46 : 52,
    borderRadius: compactHeight ? 23 : 26,
    borderWidth: 1,
    borderColor: 'rgba(255, 212, 59, 0.7)',
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    shadowColor: '#FFD43B',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  languageText: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 14 : 15,
    fontWeight: '700',
  },
  backPill: {
    alignSelf: 'flex-start',
    minWidth: compactHeight ? 104 : 114,
    height: compactHeight ? 44 : 50,
    borderRadius: compactHeight ? 22 : 25,
    borderWidth: 1,
    borderColor: 'rgba(255, 212, 59, 0.7)',
    backgroundColor: 'rgba(0, 0, 0, 0.62)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#FFD43B',
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  hero: {
    alignItems: 'center',
    paddingTop: compactHeight ? 46 : 66,
    paddingBottom: compactHeight ? 6 : 10,
  },
  signupHero: {
    alignItems: 'center',
    paddingTop: compactHeight ? 14 : 24,
    paddingBottom: compactHeight ? 4 : 8,
  },
  middleSection: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: compactHeight ? 18 : 30,
    paddingBottom: compactHeight ? 8 : 16,
  },
  logoFrame: {
    width: compactHeight ? 150 : 172,
    height: compactHeight ? 120 : 138,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: compactHeight ? 6 : 8,
  },
  logoImage: {
    width: '100%',
    height: '100%',
  },
  brandTitle: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 26 : 31,
    lineHeight: compactHeight ? 30 : 36,
    fontWeight: '900',
    textAlign: 'center',
  },
  brandAccent: {
    color: '#FFB526',
    fontSize: compactHeight ? 26 : 31,
    lineHeight: compactHeight ? 30 : 36,
    fontWeight: '900',
    textAlign: 'center',
  },
  taglineRow: {
    width: '84%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: compactHeight ? 4 : 6,
    marginBottom: compactHeight ? 4 : 6,
  },
  taglineLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 198, 37, 0.58)',
  },
  taglineMark: {
    width: compactHeight ? 40 : 48,
    height: compactHeight ? 9 : 11,
    borderRadius: 8,
    backgroundColor: '#E80016',
    marginHorizontal: 16,
    transform: [{ rotate: '-16deg' }],
  },
  tagline: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 11 : 13,
    lineHeight: compactHeight ? 15 : 18,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: compactHeight ? 6 : 10,
  },
  loginCard: {
    width: '88%',
    maxWidth: 360,
    alignSelf: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(255, 212, 59, 0.86)',
    backgroundColor: 'rgba(32, 30, 10, 0.76)',
    paddingHorizontal: cardPadding,
    paddingTop: compactHeight ? 14 : 18,
    paddingBottom: compactHeight ? 14 : 18,
    shadowColor: '#FFD43B',
    shadowOpacity: 0.48,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  cardTitle: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 23 : 28,
    lineHeight: compactHeight ? 28 : 34,
    fontWeight: '900',
    textAlign: 'center',
  },
  cardTitleAccent: {
    color: '#FFD43B',
    textDecorationLine: 'underline',
  },
  cardSubtitle: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 13 : 15,
    lineHeight: compactHeight ? 18 : 21,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: compactHeight ? 4 : 8,
    marginBottom: compactHeight ? 8 : 14,
  },
  label: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 12 : 14,
    lineHeight: compactHeight ? 17 : 20,
    fontWeight: '800',
    marginBottom: compactHeight ? 4 : 6,
  },
  inputShell: {
    height: compactHeight ? 44 : 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    backgroundColor: 'rgba(0, 0, 0, 0.16)',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    marginBottom: compactHeight ? 8 : 12,
  },
  field: {
    flex: 1,
    height: '100%',
    color: '#FFFFFF',
    fontSize: compactHeight ? 13 : 15,
    lineHeight: compactHeight ? 19 : 22,
    fontWeight: '600',
    paddingHorizontal: 12,
    paddingVertical: 0,
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  inputIcon: {
    width: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyeIcon: {
    color: '#FFFFFF',
    fontSize: 20,
    lineHeight: 22,
    fontWeight: '900',
  },
  genderRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: compactHeight ? 8 : 12,
  },
  genderOption: {
    flex: 1,
    height: compactHeight ? 38 : 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    backgroundColor: 'rgba(0, 0, 0, 0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  genderOptionActive: {
    borderColor: '#FFD43B',
    backgroundColor: '#D50000',
  },
  genderText: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 11 : 13,
    fontWeight: '800',
    textAlign: 'center',
  },
  genderTextActive: {
    color: '#FFFFFF',
  },
  forgotText: {
    color: '#FFD43B',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    textAlign: 'right',
    marginTop: -6,
    marginBottom: compactHeight ? 10 : 16,
  },
  button: {
    width: '68%',
    height: compactHeight ? 48 : 56,
    alignSelf: 'center',
    borderRadius: 15,
    overflow: 'hidden',
    shadowColor: '#E80016',
    shadowOpacity: 0.44,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 8,
  },
  buttonDisabled: {
    opacity: 0.72,
  },
  buttonGradient: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 18 : 21,
    lineHeight: compactHeight ? 24 : 28,
    fontWeight: '900',
  },
  signUpRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: compactHeight ? 12 : 18,
    marginBottom: compactHeight ? 4 : 8,
  },
  signUpLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 212, 59, 0.7)',
  },
  signUpCopy: {
    color: '#FFFFFF',
    fontSize: compactHeight ? 12 : 14,
    fontWeight: '700',
    marginHorizontal: 12,
  },
  signUpText: {
    color: '#FFD43B',
    fontSize: compactHeight ? 17 : 19,
    lineHeight: compactHeight ? 22 : 25,
    fontWeight: '900',
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.62)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  disclaimerCard: {
    width: '100%',
    maxHeight: '78%',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#FFD43B',
    backgroundColor: '#151306',
    padding: 18,
  },
  disclaimerTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  disclaimerIntro: {
    color: '#FFD43B',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    marginTop: 6,
    marginBottom: 12,
  },
  disclaimerScroll: {
    maxHeight: 250,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 212, 59, 0.46)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    paddingHorizontal: 12,
    paddingTop: 10,
  },
  disclaimerText: {
    color: '#F8F1D0',
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
    marginBottom: 10,
  },
  acceptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#FFD43B',
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxActive: {
    backgroundColor: '#D50000',
    borderColor: '#D50000',
  },
  checkboxIcon: {
    color: '#FFFFFF',
    fontSize: 17,
    lineHeight: 19,
    fontWeight: '900',
  },
  acceptText: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
  },
  cancelButton: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFD43B',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  cancelText: {
    color: '#FFD43B',
    fontSize: 14,
    fontWeight: '900',
  },
  acceptButton: {
    flex: 1.4,
    height: 46,
    borderRadius: 12,
    backgroundColor: '#D50000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  acceptButtonDisabled: {
    backgroundColor: '#725C3B',
  },
  acceptButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
});

export default styles;
